# \u5F00\u53D1\u73AF\u5883\u914D\u7F6E
server:
  # \u670D\u52A1\u7AEF\u53E3
  port: 8765
  servlet:
    # \u9879\u76EEcontextPath
    context-path: /task
  tomcat:
    # tomcat\u7684URI\u7F16\u7801
    uri-encoding: UTF-8
    # tomcat\u6700\u5927\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u4E3A200
    max-threads: 800
    # Tomcat\u542F\u52A8\u521D\u59CB\u5316\u7684\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u503C25
    min-spare-threads: 30


# Spring\u914D\u7F6E
spring:
  # \u670D\u52A1\u6A21\u5757
  devtools:
    restart:
      # \u70ED\u90E8\u7F72\u5F00\u5173
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://192.168.151.126:3306/badmin?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&serverTimezone=UTC
      username: root
      password: 123456
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    #\u65E5\u671F\u683C\u5F0F\u5316
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
