boz:
  name: boz
  version: 1.0.1
  copyrightYear: 2019
  profile: D:/profile/
  max-filesize: 1MB
  max-filename-length: 1000


# 开发环境配置
server:
  # 服务端口
  port: 8888
  servlet:
    # 项目contextPath
    context-path: /basic
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# Spring配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://192.168.151.126:3306/badmin?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&serverTimezone=UTC
      username: root
      password: 123456
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      #单个文件大小
      max-file-size: 20MB
      #总文件大小
      max-request-size: 20MB
